### PR TITLE
Update to 6.2.36.

### PR DESCRIPTION
**Pull request by ikedas**

### CODE REVIEW

**Comment by xavierba** [comment]
Looks good.

**Comment by xavierba** [comment]
Actually, it's not perfect.
```#%global pre_rel b.1``` is causing a problem. It should be ```#global pre_rel b.1```
The leading # doesn't prevent the %global macro to be expanded and thus pre_rel is set to b.1, causing the copr build to fail because it indeed can't fetch https://github.com/sympa-community/sympa/releases/download/6.2.36b.1/sympa-6.2.36b.1.tar.gz and would also cause more issues down the line.

**Comment by xavierba** [comment]
I have pushed the one character fix to the master branch in my fork and am running the copr build again. I'll push to the master branch of yours w/o a PR if it succeed.

**Comment by xavierba** [comment]
https://github.com/sympa-community/sympa/releases/download/6.2.36/sympa-6.2.36.tar.gz doesn't exist either at the moment but that's not an issue with the spec file.

**Comment by ikedas** [comment]
@xavierba, thanks for suggestion. I'll commit a fix.

6.2.36 will (hopefully) be released at 23 Sep.

**Pull request merged**
