### PR TITLE
PR 20171201

### PR DESCRIPTION
**Pull request by xavierba**
Hi @ikedas ,

Here's a new pull request that enhances and replaces the previous one.
It hopefully properly incorporates the feedback you gave me on the previous one (https://github.com/ikedas/sympa-rpm/pull/10).
The most notable addition is it now adds the aliases file move to /etc/sympa/aliase, which is not forward compatible to your own RPMs.

Regards,
Xavier

### CODE REVIEW

**Comment by ikedas** [comment]
Excellent fixes and improvements @xavierba!

However my only concern is the change on aliases you said.  You merged two alias files:
- Robot alias file: Defines aliases _not_ managed by Sympa (``sympa``, ``listmaster``, ``bounce``, ...).
- List alias file: Defines list aliases managed by Sympa (list address, ``*-owner``, ``*-request``, ...). Its location is defined by options such as ``--with-alias_file``.

Former may be customized by users, e.g. adding aliases excluded from list services. Latter will be updated by Sympa alias manager and not suit for manual customization (otoh ``sympa.pl --make_alias_file`` creates only list alias entries).  I suppose that's why alias files were split into two.

**Comment by xavierba** [comment]
Glad to read you're happy with the changes :-)
I believe the change to the alias handling would be better discussed on its own in a separate issue. I'll open one once I've taken another fresh look at it.
Meanwhile, what's the best course of action to get the other changes merged ? Shall I just drop the alias commit and force push to the PR-20171201 branch or is it better to open another PR ? Or maybe it's already fine and you can do the merge w/o the alias commit ? Sorry for the stupid questions, I'm still learning...

**Comment by ikedas** [comment]
@xavierba,
> Meanwhile, what's the best course of action to get the other changes merged ? Shall I just drop the alias commit and force push to the PR-20171201 branch or is it better to open another PR ? Or maybe it's already fine and you can do the merge w/o the alias commit ? Sorry for the stupid questions, I'm still learning...

I prefer to update existing PR: Merging conflict and reverting changes on alias on your clone, then pushing it.  ...But TMTOWTDI. Please feel free to do how you feel easy!

**Comment by xavierba** [comment]
OK, the merge conflict is resolved and the alias commit has been dropped.

**Comment by ikedas** [comment]
@xavierba, sorry for delayed checking. Now I'm ok at all.

In this time, since you submitted, I'll merge.

**Pull request merged**
