### PR TITLE
scriptlets cleanup mostly

### PR DESCRIPTION
**Pull request by xavierba**
- scriptlets cleanup
- fix for a bogus changelog date
- patch to fix smtpc build warnings

### CODE REVIEW

**Comment by xavierba** [comment]
Oops, more than what I initially wanted to send to you was pulled. Hopefully, you're ok with the other changes. Sorry, I'm not used enough to git/github.

**Comment by ikedas** [comment]
If you don't mind, I'd like to revert https://github.com/ikedas/sympa-rpm/pull/2/commits/016ba31. IMHO different format of version number (6.2.19-0.1.b.2) from upstream (6.2.19b.2) may confuse users.

**Comment by xavierba** [comment]
This change is intended to match Fedora packaging guidelines:
https://fedoraproject.org/wiki/Packaging:Versioning
I admit this may be a bit confusing when you are not used to it, but only for pre-releases.
For some examples, see also:
https://fedoraproject.org/wiki/Package_Versioning_Examples

Here we are dealing with a pre-release, so the successive release and version will be:
sympa-6.2.19-0.1.b.1 for 2.6.19 beta 1
sympa-6.2.19-0.2.b.2 for 2.6.19 beta 2
sympa-6.2.19-1 for 2.6.19 final
sympa-6.2.19-2 for 2.6.19 final + packaging change or added patch
...
This wouldn't work if the pre-release state is kept in the version, as sympa-2.6.19b.1-1 would be considered newer than sympa-2.6.19-1

**Comment by ikedas** [comment]
There was a short discussion on this issue at upstream: [sympa/Issue#21](https://github.com/sympa-community/sympa/issues/21). So the next stable release on upstream is not "6.2.19final" but "6.2.20".

Though I can't decide which method is better, I think release number may not be dependent on upstream version number.

**Comment by xavierba** [comment]
The purpose of this guideline is exactly that: make sure rpm version and release are independent from upstream release numbering. The downstream packager has to adapt to what upstream do to make sure rpm version and release increase monotonically. 

What upstream does can be discuss indeed.

One possible and not too much disruptive change could be to use 6.2.19beta1 rather than sympa 6.2.19b.1, it would make the pre-release status more obvious to everyone, as 6.2.19b.1 could very much be seen as a fixup for 6.2.19 release, as some upstreams do. This would then make the rpm sympa-6.2.19-0.1.beta1.

Sympa could also decide to use even number for stable releases and odd numbers for development releases. 6.2.18 would be stable, 6.2.19.1 would be the first beta, 6.2.19.2 second beta, and 6.2.20 would be stable, as was done for linux kernel before. I'm not very fond of this one though.

**Pull request merged**
